#!/usr/bin/env bash
# Bring a test VM to the exact state the campaign expects, from nothing.
#
# Idempotent: safe to re-run. Everything it installs lives under the login
# user's home so a re-provision of a fresh VM is one command.
#
#   scripts/perf/staging/provision.sh            # everything
#   scripts/perf/staging/provision.sh scripts    # just re-push the harnesses
#   scripts/perf/staging/provision.sh corpus     # just (re)build the dufs corpus
#   scripts/perf/staging/provision.sh check      # report what is present
#
# What lives where afterwards, on the VM:
#   ~/env.sh          coordinates + credentials (chmod 600, NEVER in the repo)
#   ~/bore            the bore binary under test
#   ~/dufs ~/oha      the real-application origin and the latency load generator
#   ~/vm_*.sh         the VM-side harnesses
#   ~/out ~/res       per-run logs and resource samples
#   ~/dufsroot        the served corpus (~1.2 GiB, disk-guarded)
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/lib.sh"

STEP="${1:-all}"
do_step(){ case "$STEP" in all|"$1") return 0;; *) return 1;; esac; }

DUFS_VER="${DUFS_VER:-0.43.0}"
OHA_VER="${OHA_VER:-1.4.5}"

if do_step packages; then
  say "packages"
  vm "sudo -n DEBIAN_FRONTEND=noninteractive apt-get -qq update >/dev/null 2>&1;
      sudo -n DEBIAN_FRONTEND=noninteractive apt-get -qq install -y \
        jq curl python3 sshpass ethtool iproute2 unzip ca-certificates docker.io >/dev/null 2>&1;
      mkdir -p ~/out ~/res;
      echo '  apt ok'; docker --version 2>/dev/null || echo '  (docker missing)'"
fi

if do_step binary; then
  say "bore binary"
  # The binary under test must match the VM's architecture. A locally built
  # release is used when its target triple matches; otherwise the VM builds
  # nothing and the operator is told, because silently benchmarking a
  # DIFFERENT binary than the one being reviewed is the worst possible outcome.
  ARCH=$(vm "uname -m" | tr -d '\r')
  LOCAL_ARCH=$(uname -m)
  BIN_SRC="${BORE_BIN:-$HERE/../../../target/release/bore}"
  if [ -x "$BIN_SRC" ] && [ "$ARCH" = "$LOCAL_ARCH" ]; then
    vmcp "$BIN_SRC" "$BORE_VM_USER@$BORE_VM:~/bore"
    echo "  pushed local release build ($LOCAL_ARCH)"
  else
    echo "  VM is $ARCH, this host is $LOCAL_ARCH — pushing nothing."
    echo "  Put a matching binary at ~/bore on the VM yourself (a release"
    echo "  artifact, or 'cargo build --release' on the VM), then re-run 'check'."
  fi
  vm "chmod +x ~/bore 2>/dev/null; ~/bore --version 2>/dev/null || echo '  no ~/bore yet'"
fi

if do_step tools; then
  say "dufs + oha"
  vm "set -e
    a=\$(uname -m); case \$a in x86_64) d=x86_64-unknown-linux-musl;; aarch64) d=aarch64-unknown-linux-musl;; *) echo unsupported \$a; exit 1;; esac
    [ -x ~/dufs ] || { curl -fsSL -o /tmp/dufs.zip https://github.com/sigoden/dufs/releases/download/v$DUFS_VER/dufs-v$DUFS_VER-\$d.zip && unzip -oq /tmp/dufs.zip -d ~ && chmod +x ~/dufs; }
    [ -x ~/oha ] || { curl -fsSL -o ~/oha https://github.com/hatoo/oha/releases/download/v$OHA_VER/oha-linux-\$( [ \$a = x86_64 ] && echo amd64 || echo arm64 ) && chmod +x ~/oha; }
    ~/dufs --version; ~/oha --version"
fi

if do_step scripts; then
  say "harnesses"
  vmcp "$HERE"/vm/*.sh "$BORE_VM_USER@$BORE_VM:~/"
  vmcp "$HERE"/res/res_sampler.sh "$BORE_VM_USER@$BORE_VM:~/"
  vm "chmod +x ~/vm_*.sh ~/driver.sh ~/res_sampler.sh 2>/dev/null; ls -1 ~/vm_*.sh | wc -l | xargs echo '  vm scripts:'"

  # The VM-side env.sh is DERIVED from the workstation one so the two can never
  # drift, and is written with mode 600. It is not, and must never be, in git.
  say "VM env.sh (mode 600, not in git)"
  vm "cat > ~/env.sh <<'VMENV'
# Generated by scripts/perf/staging/provision.sh — do not edit by hand.
export BORE_SECRET='$BORE_SECRET'
export ADMIN_TOKEN='$ADMIN_TOKEN'
export BORE_TO='$BORE_TO'
export ADMIN_URL='$ADMIN_URL'
export SSHGW_USER='${SSHGW_USER:-}'
export SSHGW_PASS='${SSHGW_PASS:-}'
# short names the VM-side harnesses use
export GW='$BORE_GW'
export SRV='${BORE_SRV:-}'
export VM_HOME=\"\$HOME\"
export IFACE='$BORE_SRV_IFACE'
export DUFS_PORT='${BORE_DUFS_PORT:-5080}'
export ORIGIN_PORT='${BORE_ORIGIN_PORT:-5052}'
VMENV
chmod 600 ~/env.sh; echo '  ~/env.sh written'"
fi

if do_step image; then
  say "published docker client image"
  vm "sudo -n docker pull -q ghcr.io/manprint/bore:client >/dev/null 2>&1 &&
      sudo -n docker image inspect ghcr.io/manprint/bore:client \
        --format '  revision={{index .Config.Labels \"org.opencontainers.image.revision\"}}'"

  # The reference forwarder compose: the configuration the campaign concluded is
  # optimal, with the measurement quoted on every line. Installed STOPPED — the
  # dufs behind it has a writable upload zone and must not sit on the internet
  # unattended. `.env` is generated here (mode 600) so the compose itself stays
  # free of credentials and can be copied anywhere.
  say "reference forwarder compose (installed, not started)"
  vmcp "$HERE"/vm/docker-compose.forwarder.yml "$BORE_VM_USER@$BORE_VM:/tmp/bore-forwarder-compose.yml"
  vm "mkdir -p ~/bore-forwarder && mv /tmp/bore-forwarder-compose.yml ~/bore-forwarder/docker-compose.yml
      cat > ~/bore-forwarder/.env <<'FWENV'
BORE_SERVER=$BORE_TO
BORE_SECRET=$BORE_SECRET
BORE_VHOST_SUBDOMAIN=${BORE_FORWARDER_LABEL:-vmdufs}
BORE_VHOST_ID=${BORE_FORWARDER_LABEL:-vmdufs}
FWENV
      chmod 600 ~/bore-forwarder/.env
      echo '  ~/bore-forwarder/{docker-compose.yml,.env} written (start with: cd ~/bore-forwarder && sudo docker compose up -d)'"
fi

if do_step corpus; then
  say "dufs corpus (disk-guarded at 2 GiB free)"
  vm "~/vm_dufs_setup.sh setup && ~/vm_dufs_setup.sh start && ~/vm_dufs_setup.sh status"
fi

say "check"
vm "echo '  bore:  '\$(~/bore --version 2>/dev/null || echo MISSING)
    echo '  dufs:  '\$(~/dufs --version 2>/dev/null || echo MISSING)
    echo '  oha:   '\$(~/oha --version 2>/dev/null || echo MISSING)
    echo '  env:   '\$( [ -f ~/env.sh ] && stat -c %a ~/env.sh || echo MISSING)
    echo '  disk:  '\$(df -Pm / | awk 'NR==2{print \$4\" MiB free\"}')
    echo '  vhosts registered right now: '\$(pgrep -fc 'bore vhost' 2>/dev/null || echo 0)"
if [ -n "$BORE_SRV" ]; then
  say "server host reachability"
  srv "echo '  uname: '\$(uname -m); echo '  allowance counter: '\$(sudo -n ethtool -S $BORE_SRV_IFACE 2>/dev/null | grep -c bw_in_allowance_exceeded)" \
    || echo "  server host not reachable — server-side steps will be skipped"
fi
